require("core.plugin-config.colorscheme")
require("core.plugin-config.lualine")
require("core.plugin-config.nvim-tree")
require("core.plugin-config.telescope")
require("core.plugin-config.treesitter")
require("core.plugin-config.lsp-config")
require("core.plugin-config.completions")
